name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: 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
        TARGET_REPO: jiayechao/teamsite
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm install && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist